global:
  stmp_smarthost: 'smtp.sendgrid.net:587'
  smtp_from: 'Alert Manager <alertmanager@example.com>'
  stmp_auth_username: 'bjornvanbruchem'
  smtp_auth_password: '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'

  receivers:
    - name: mail
      email_configs:
        - to: 'b.vanbruchem1@student.avans.nl'
          headers:
            Subject: 'Alert ({{ .Status }}): {{ .CommonLabels.severity }} {{ .CommonAnnotations.message }} ({{ .CommonLabels.alertname }})'
          html: |
            Greetings,
                    <p>
                    You have the following firing alerts:
                    <ul>
                    {{ range .Alerts }}
                    <li>{{.Labels.alertname}} on {{.Labels.instance}}</li>
                    <li>Labels:</li>
                    <li>{{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}</li>
                    <li>{{ end }}Annotations:</li>
                    <li>{{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}</li>
                    <li>{{ end }}---</li>
                    {{ end }}
                    </ul>
                    </p>
  route:
    group_wait: 10s
    group_interval: 5m
    receiver: mail
    repeat_interval: 10s
    routes:
      - match:
          severity: High
        repeat_interval: 1m
        receiver: slack