global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: 'node-app'
    static_configs:
      - targets: [ 'devops_app:3050' ]

  - job_name: 'database'
    static_configs:
      - targets: [ 'devops_db_exporter:9216' ]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - prometheus-alertmanager:80