name: 'DevOps NodeJS CI for Chat App'

on:
  push:
    paths:
      - ./chat-app/**
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 21.5 ]

    defaults:
      run:
        working-directory: ./chat-app/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Jest code coverage
        run: npm run coverage